# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Disco Self

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'BuildJob'
    steps:
      - script: echo "Build"
        displayName: 'Build app'
      - task: ServiceNow-DevOps-Agent-Artifact-Registration@1
        inputs:
          connectedServiceName: 'PDI'
          artifactsPayload: |
            {
              "artifacts": [
                {
                   "name": "_Test One",
                   "version": "1.$(Build.BuildId)",
                   "semanticVersion": "1.$(Build.BuildId).0",
                   "repositoryName": "Test One"
                }
              ]
            }


- stage: Test
  displayName: 'Test Stage'
  jobs:
  - job: Unit_tests
    displayName: 'TestJob'
    steps:
      - script: echo "Unit Tests"
        displayName: 'UnitTests'

  - job: Checkmarx_Scan
    displayName: 'CheckmarxJob'
    steps:
      - script: echo "Checkmarx Scan"
        displayName: 'CheckmarxScript'


- stage: Deploy
  displayName: 'DeployStage'
  jobs:
  - job: UAT_Deploy
    displayName: 'UATJob'
    steps:
      - script: echo "UAT Deploy"
        displayName: 'UATScript'
      - task: ServiceNow-DevOps-Agent-Package-Registration@1
        inputs:
          connectedServiceName: 'PDI'
          packageName: 'Test Package 1'
          artifactsPayload: |
            {
                "artifacts": [
                    {
                        "name": "Test Artifact One",
                        "repositoryName": "Test One",
                        "version": "1.$(build.buildId)",
                        "currentBuildInfo": "true"
                    }
                ]
            }

  - job: Production_Deploy
    displayName: 'ProductionJob'
    steps:
      - script: echo "Production Deploy"
        displayName: 'DeployScript'